### PR TITLE
Fix river api

### LINKED ISSUE #18: putRiver does not work because wrapper function mistreats its arguments
When trying to use Client#putRiver with the latest npm module (0.0.12), the command fails without error message. 

The reason why it fails is that the Client.putRiver method is created by the wrapIndexMethod function (https://github.com/ramv/node-elastical/blob/master/lib/client.js#L1052) which removes the first argument from the given function. 

This results in Index.putRiver called without the name parameter, because it is sliced off by the wrapIndexMethod implementation.

The arguments to putRiver are (name, config, callback), which when called becomes Index#putRiver(client, config, callback) instead of the intended Index#putRiver(client, name, config, callback).

### PR DESCRIPTION
**Pull request by francov**
This fix should close #18.
Client `putRiver`, `getRiver` and `deleteRiver` methods are created using the `wrapIndexMethod` helper: this results in Index methods being called without the name parameter. Using `wrapStaticIndexMethod` solved the problem.

### CODE REVIEW

File: tests/offline-tests.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ vows.describe('Elastical').addBatch({
                     },
 
                     'URL should not have a query string': function (err, options) {
-                        assert.isUndefined(parseUrl(options.uri).search);
+                        assert.isNull(parseUrl(options.uri).search);
```
Comment (francov) [inline tests/offline-tests.js:68]: It seems that the `search` property is null and not undefined

File: tests/online-tests.js [hunk 2]
```diff
@@ -1029,7 +1029,7 @@ vows.describe('Elastical')
 
         '`putRiver()`': {
             topic: function (client) {
-                client.putRiver( 'elastical-test-river', 'elastical-test-river-put', { type:'dummy' }, this.callback );
```
Comment (francov) [inline tests/online-tests.js:1032]: This kind of test was wrong because `'elastical-test-river'` is neither an index name nor a river name. So this simply hide the bug.
